---
- name: Create installation directory
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory
  tags:
    - install

- name: Download Zookeeper archive ({{ archive_url }})
  become: true
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ (archive_checksum|length > 0) | ternary(checksum_format+':'+archive_checksum, '') }}"
    mode: '0775'
    force: '{{ force }}'
  register: archive_tmp
  tags:
    - install

- name: Extract Zookeeper archive
  become: true
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
  tags:
    - install

- name: Copy Zookeeper configuration in place
  become: true
  template:
    src: "{{ zookeeper_conf }}.j2"
    dest: "{{ install_dir }}/conf/{{ zookeeper_conf }}"
    force: true
  tags:
    - install
    - start
    - restart
    - update

- name: Create Zookeeper data directory
  become: true
  file:
    path: "{{ zookeeper_data_dir }}"
    state: directory
  tags:
    - install

- name: Create Zookeeper myid File
  template:
    src: myid.j2
    dest: "{{zookeeper_data_dir}}/myid"
    mode: '0775'
  tags:
    - install

- name: Start Zookeeper server
  become: true
  shell: 'source /root/.bashrc && {{ install_dir }}/bin/zkServer.sh start'
  tags:
    - start

- name: Stop Zookeeper server
  become: true
  shell: 'source /root/.bashrc && {{ install_dir }}/bin/zkServer.sh stop'
  tags:
    - stop    