---
archive_url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
archive_checksum: 68f3802c2dd3980667e4ba65ea2e1fb03f4a4ba026cca375f15a0390ff850949
checksum_format: sha256
force: no

install_dir: /opt/node_exporter

web_listen_address: "0.0.0.0:9100"
web_telemetry_path: "/metrics"
textfile_dir: "/tmp"

flags: "--web.listen-address={{ web_listen_address }} --collector.textfile.directory={{ textfile_dir }}"