---
- name: Create installation directory
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory
  tags:
    - install

- name: Download node_exporter archive ({{ archive_url }})
  become: true
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ (archive_checksum|length > 0) | ternary(checksum_format+':'+archive_checksum, '') }}"
    mode: '0775'
    force: '{{ force }}'
  register: archive_tmp
  tags:
    - install

- name: Extract node_exporter archive
  become: true
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
  tags:
    - install

- name: Add Scripts
  template:
    src: 'templates/{{ item }}'
    dest: '{{ install_dir }}/scripts/'
    mode: '0775'
  loop:
    - 'start.sh'
    - 'stop.sh'
    - 'restart.sh'
    - 'control.sh'

  tags:
    - install
    - start
    - stop
    - restart
    - update


- name: Start node_exporter server
  become: true
  shell: '{{ install_dir }}/scripts/start.sh {{ flags }}'
  tags:
    - install
    - start

- name: Stop node_exporter server
  become: true
  shell: '{{ install_dir }}/scripts/stop.sh'
  tags:
    - stop

- name: Restart node_exporter server
  become: true
  shell: '{{ install_dir }}/scripts/restart.sh {{ flags }}'
  tags:
    - restart
