---
- name: Create installation directory
  become: true
  file:
    path: "{{ install_dir }}"
    state: directory
  tags:
    - install

- name: Download Prometheus archive ({{ archive_url }})
  become: true
  get_url:
    url: "{{ archive_url }}"
    dest: "/tmp/{{ archive_url | urlsplit('path') | basename }}"
    checksum: "{{ (archive_checksum|length > 0) | ternary(checksum_format+':'+archive_checksum, '') }}"
    mode: '0775'
    force: yes
  register: archive_tmp
  tags:
    - install

- name: Extract Prometheus archive
  become: true
  unarchive:
    src: "{{ archive_tmp.dest }}"
    dest: "{{ install_dir }}"
    mode: '0775'
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
  tags:
    - install

- name: Copy Prometheus configuration in place
  become: true
  template:
    src: "{{ prometheus_config_file }}.j2"
    dest: "{{ install_dir }}/{{ prometheus_config_file }}"
    force: true
  tags:
    - install
    - start
    - restart
    - update
    - reload

- name: Add Scripts
  template:
    src: 'templates/{{ item }}'
    dest: '{{ install_dir }}/scripts/'
    mode: '0775'
  loop:
    - 'start.sh'
    - 'stop.sh'
    - 'restart.sh'
    - 'reload.sh'
  tags:
    - install
    - start
    - stop
    - restart


- name: Start Prometheus server
  become: true
  shell: '{{ install_dir }}/scripts/start.sh'
  tags:
    - install
    - start

- name: Stop Prometheus server
  become: true
  shell: '{{ install_dir }}/scripts/stop.sh'
  tags:
    - stop

- name: Restart Prometheus server
  become: true
  shell: '{{ install_dir }}/scripts/restart.sh'
  tags:
    - restart

- name: Reload Prometheus server
  become: true
  shell: '{{ install_dir }}/scripts/reload.sh'
  tags:
    - reload