apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

datasources:
  - name: prometheus
    type: prometheus
    orgId: 1
    access: proxy
    url: http://localhost:9090
    # <bool> allow users to edit datasources from the UI.
    editable: false
